<?php

/**
 * SourceKnowledge Shopping Ads
 *
 * PHP version 7
 *
 * Copyright © Sourceknowledge. All rights reserved.
 * See LICENSE.txt for license details.
 *
 * @category  SourceKnowledge
 * @package   Sourceknowledge_ShoppingAds
 * @author    SourceKnowledge Development <dev@sourceknowledge.com>
 * @copyright 2020 Sourceknowledge. All rights reserved.
 * @license   LICENSE.txt GNU GENERAL PUBLIC LICENSE
 * @link      https://www.sourceknowledge.com/
 */

/** @var Sourceknowledge\ShoppingAds\Block\AbstractPixel $block */
?>
<noscript>
    <img height="1"
         width="1"
         src="//upx.provenpixel.com/mage.js.php?noscript=1&shop="<?= /* @noEscape */ $block->getQueryParams() ?>/>
</noscript>
<script type="text/x-magento-init">
{
    "*": {
        "Sourceknowledge_ShoppingAds/js/pixel-code": {
            "query": "<?= /* @noEscape */ $block->getQueryParams() ?>"
        }
    }
}
</script>
